In [1]:
#import the tensorflow libraries 
import tensorflow as tf

/anaconda/envs/tensorflow/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


In [6]:
#initialise the variables using the tensorflow import statements 
x = tf.Variable(3, name = "x")
y = tf.Variable(4, name = "y")
f = x*x*y + y + 2

In [7]:
#this creates a new session to initialize the variables and carry out the operations 
mysess = tf.Session()

In [8]:
#initializes the variable x 
mysess.run(x.initializer)

In [9]:
#initializes the variable y  
mysess.run(y.initializer)


In [10]:
# store the value obtained in the operation in the variable result 
result = mysess.run(f)

In [11]:
print(result)

42


In [12]:
#this closes the session and frees up the resources 
mysess.close()

In [13]:
#this is much easy rather than calling the sess.run all the time .... the sesion closes at the end of with block 
with tf.Session() as mysess:
    x.initializer.run()
    y.initializer.run()
    result = f.eval()

In [14]:
print(result)

42


In [15]:
#this will initialize all the variables when it is run 
init = tf.global_variables_initializer()

In [16]:
with tf.Session() as mysess:
    init.run() #initialises all the variables 
    result = f.eval()

In [17]:
print(result)

42


In [18]:
mysess = tf.InteractiveSession()

In [19]:
init.run()
result = f.eval()
print(result)

42


In [20]:
mysess.close()#you need to close the session manually when you use an InteractuveSession rather than a regulat Session 

In [22]:
#the node is added to the default graph 
x1 = tf.Variable(1)

x1.graph is tf.get_default_graph()

True

In [23]:
#u can cretae an temporary graph to store the node 
graph = tf.Graph()
with graph.as_default():
    x2 = tf.Variable(2)

In [24]:
x2.graph is graph # its in the graph what we have created 

True

In [25]:
x2.graph is tf.get_default_graph() #it is not present in the original graph 

False

In [26]:
import numpy as np 

In [27]:
from sklearn.datasets import fetch_california_housing

In [28]:
housing = fetch_california_housing()

In [29]:
m, n = housing.data.shape

In [30]:
bias = np.c_[np.ones((m,1 )), housing.data]

In [31]:
x = tf.constant (bias, dtype = tf.float32, name = "x")
y = tf.constant (housing.target.reshape(-1, 1 ), dtype = tf.float32, name = "y")
xt = tf.transpose(x)

In [32]:
theta = tf.matmul (tf.matmul(tf.matrix_inverse(tf.matmul(xt, x)), xt), y)

In [33]:
with tf.Session() as sess :
    theta_value = theta.eval()

In [34]:
print(theta_value)

[[ -3.74651413e+01]
 [  4.35734153e-01]
 [  9.33829229e-03]
 [ -1.06622010e-01]
 [  6.44106984e-01]
 [ -4.25131839e-06]
 [ -3.77322501e-03]
 [ -4.26648885e-01]
 [ -4.40514028e-01]]


In [46]:
n_epochs = 1000
rate = 0.01
x = tf.constant(bias , dtype = tf.float32, name = "x")
y = tf.constant(housing.target.reshape(-1, 1) , dtype = tf.float32, name = "y")
theta = tf.Variable(tf.random_uniform([n + 1 , 1], -1.0, 1.0), name = "theta")
y_pred = tf.matmul(x, theta, name ="predictions")
error = y_pred - y 
mse = tf.reduce_mean (tf.square(error), name = "mse")
gradients = tf.gradients(mse, [theta])[0]
op = tf.assign(theta, theta - rate * gradients)
init = tf.global_variables_initializer()

In [47]:
with tf.Session() as sess:
    sess.run(init)
    for epoch in range (n_epochs):
        if epoch % 100 == 0:
            print("epoch", epoch , "MSE=", mse.eval())
            sess.run(op)
            best_theta = theta.eval()

epoch 0 MSE= 3.15491e+06
epoch 100 MSE= 1.39406e+16
epoch 200 MSE= 6.16233e+25
epoch 300 MSE= inf
epoch 400 MSE= inf
epoch 500 MSE= inf
epoch 600 MSE= inf
epoch 700 MSE= inf
epoch 800 MSE= inf
epoch 900 MSE= nan


In [48]:
a = tf.placeholder(tf.float32, shape=(None, 3))
b = a+ 5
with tf.Session() as sess:
    b_e1 = b.eval(feed_dict={a : [[1,2,3]]})
    b_e2 = b.eval(feed_dict={a : [[4,5,6], [7,8,9]]})
    

In [49]:
print(b_e1)

[[ 6.  7.  8.]]


In [50]:
print(b_e2)

[[  9.  10.  11.]
 [ 12.  13.  14.]]


In [51]:
x =tf.placeholder(tf.float32, shape=(None, n+1), name="x")
y = tf.placeholder(tf.float32, shape=(None, 1), name="y")
batch_size = 100
n_batches =int(np.ceil(m / batch_size))

In [ ]:
##just an test line 